name: "redpanda-action"
description: "Setup Redpanda"
author: "fernandes"
branding:
  icon: fast-forward
  color: red
inputs:
  redpanda_network:
    description: "Network for the kafka broker"
    required: false
    default: ""
  kafka_api_port:
    description: "Port for the Kafka API"
    required: false
    default: "9092"
  admin_api_port:
    description: "Port for the Admin API"
    required: false
    default: "9644"
  panda_proxy_port:
    description: "Port for the Panda proxy"
    required: false
    default: "8082"
  schema_registry_port:
    description: "Port for the Schema registry"
    required: false
    default: "8081"
  rpc_port:
    description: "Port for the RPC address"
    required: false
    default: "33145"
  node_id:
    description: "An id for the node"
    required: false
    default: "0"
  version:
    description: "Version of Redpanda to use"
    required: false
    default: "latest"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.redpanda_network }}
    - ${{ inputs.kafka_api_port }}
    - ${{ inputs.admin_api_port }}
    - ${{ inputs.panda_proxy_port }}
    - ${{ inputs.schema_registry_port }}
    - ${{ inputs.rpc_port }}
    - ${{ inputs.node_id }}
